# Update your configuration.yaml with the following code

variables:
  snapmaker_ip: "192.168.10.7"

rest_command:
  snapmaker_connect:
    url: 'http://{{ snapmaker_ip }}:8080/api/v1/connect'
    method: 'post'
    content_type: 'application/json'
    name: 'Connect to Snapmaker'

sensor:
  - platform: rest
    name: Snapmaker API Token
    json_attributes:
      - token
    value_template: "{{ value_json.token }}"
    resource: "http://localhost:8123/api/rest_command/snapmaker_connect"
    method: POST
    headers:
      content-type: application/json
  - platform: rest
    name: Snapmaker Status
    resource: "http://{{ snapmaker_ip }}:8080/api/v1/status"
    method: GET
    json_attributes:
      - nozzleTemperature
      - printStatus
